### ISSUE TITLE
Adjoint surface sensitivity deteriorates with mesh refinement. 

### ISSUE THREAD

**Issue by pedropaulocb** [mdolab/adflow#170]
I have been trying to work with adjoint using Adflow to calculate surface sensitivities. 

The direct simulations worked fine for all mesh refinements (coarse, medium, fine, etc.).  However, when computing the surface sensitivity to lift or drag, the sensitivity changes significantly with the level of refinement until oscillations start to appear in the results (for more refined meshes).

The direct simulations converged well for L2Convergence<1e-12. All the adjoints also converged with res. norm < 1e-8. 
**I am not using a FDD box**, because I am interested in the sensitivity of the entire surface. It is a 2D case. 

I have tried the Bump-in-Channel and NACA0012 (2D) cases with Euler and Laminar NS. Still, all the sensitivities get oscillations when we run medium/fine meshes, and different mesh refinement always gives different sensitivity solutions for both solvers. 

Have anyone faced this problem before or have any clue about what may be causing these problems?

I am attaching two pictures here (Bump-in-Channel for Mach=0.3) and the script used to run the laminar N

![Laminar_Sens_dZ_Drag](https://user-images.githubusercontent.com/86976101/139069112-8b783fb2-e3a8-4c8c-ab14-65dd2018bd71.png)
![bump_geometry](https://user-images.githubusercontent.com/86976101/139069843-89e3358d-d748-4f3b-a399-27411b641386.png)
[bump_python_script.txt](https://github.com/mdolab/adflow/files/7426246/bump_python_script.txt)

**Comment by pedropaulocb** [comment]
@awccopp, could you explain in a little more detail how to do that? (setting your states to the adjoint vector)

**Comment by pedropaulocb** [comment]
Hi, we found out something. 
@joanibal  In the previous posts, we plotted a smooth Cp distribution obtained using python script and the **CFDSolver.addslice('y',[-0.5])** command. However, following the suggestion of @awccopp, I took a look at the adjoint field, and we realized that they were not smooth! 

I had a false impression that the solution was smooth because I looked at the data with the **addslice** function and python scripts. However, when using the volume and surface data in Paraview, oscillations were present for all flow field variables. Here I have attached results for Density and Cp (Euler solver - Bump wall) as an example.

The oscillations in the sensitivity are due to our direct solution (which leads to an oscillatory solution for Adjoints). I should mention that this only happens as we refine the mesh with the same factor in both X and Z direction (In the Y direction, we have only one volume cell in all cases)! For the two lower refinement levels, I did not have this problem (Oscillations). 

Here is attached the OneDrive folder with all the files if someone would like to look. 
https://1drv.ms/u/s!AuCQ841fyvsDgehspp45ACb0I2WOCw?e=3IfFoP 

Our satisfied criteria for convergence:
L2Convergence: 1e-13
adjointL2Convergence: 1e-9

Could you give us a hint of why are we having these oscillation problems as we refine our mesh?  

![Cp_Paraview](https://user-images.githubusercontent.com/86976101/140773461-4fba49a5-358a-4569-85c2-169c418cfd2f.jpeg)

![rho_euler](https://user-images.githubusercontent.com/86976101/140770221-f3e76ded-8969-42d4-9608-9d5146dcf728.jpg)
!

**Comment by awccopp** [comment]
I believe @akleb ran into issues with refinement causing solution oscillations.

**Comment by joanibal** [comment]
The issue @akleb  had was caused by small bumps in the geometry.   

I'd check that the geometry you used for the refined mesh is smooth enough. You may need to use double precision CGNS mesh coordinates.

**Comment by akleb** [comment]
Yes, I had a problem with lack of precision in my geometry as a result of using quadratic splines rather than cubic splines in my geometry definition. I was doing the following:

1. Start with a a list of ~100 points on an RAE 2822 geometry from [UIUC](https://m-selig.ae.illinois.edu/ads/coord_database.html)
2. Use spline interpolation to fit a quadratic b-spline to the data
3. Sample an arbitrary number of points from the spline to define my new airfoil surface
4. Create a volume mesh from these newly sampled points (allows me to make arbitrarily fine meshes without having to combine and split cells).

I fixed this problem by switching the interpolating quadratic splines to interpolating cubic splines. The main takeaway for me was that the quadratic splines where not smooth enough in regions where the flow was sensitive to the geometry (airfoil leading edge). I would start by checking that the geometry you are using as enough precision to match the level of precision you would like to see in the outputs.

**Comment by joanibal** [comment]
Hi @pedropaulocb, 

Did your issue get resolved?

**Comment by joanibal** [comment]
Glad to hear that
