### ISSUE TITLE
Turbulent residual scaling

### ISSUE THREAD

**Issue by SichengHe** [mdolab/adflow#171]
## Description
We scale the residual by dividing it by volume. However, it appears that this operation has been conducted twice in ANKstep or NKstep: once by calling saResScale and the other time by calling setRVec.

### Steps to reproduce issue

1. …
2. …
3. …

### Current behavior
…

### Expected behavior
…

### Code versions

- Operating System: 
- Python: 
- OpenMPI: 
- CGNS: 
- PETSc: 
- This software:

**Comment by anilyil** [comment]
I think we multiply by volume in `saResScale` to have a consistent order of magnitude as a finite volume scheme (SA formulation itself uses sth closer to a FD approach iirc). Then in the ANK and NK solvers, we divide by volume just like any other variable so that the small cells' residuals are well represented in the nonlinear system. Then the ANK/NK scaling also applies the turbulence scaling factor, which is done to bring the turb residuals to a similar order of magnitude as the flow variables. Let me know if you have other questions about this.

**Comment by anilyil** [comment]
@SichengHe if you are happy with the explanation, can we close this issue? if not let me know and I can explain more.

**Comment by SichengHe** [comment]
@anilyil Thanks for the reply. I think it makes sense and I will close it. One remaining concern is the dimension of the variables.
