### ISSUE TITLE
Rank mismatch during compilation

### ISSUE THREAD

**Issue by chrislupp** [mdolab/adflow#175]
## Description
Compilation fails in initFlow/variableReading.F90:2270 with the message:

    Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)

This appears to be due to a change in behavior in newer gfortran versions that seem to have changed a warning to an error (according to https://github.com/ElmerCSC/elmerfem/issues/231)

### Apparent Solution

Adding "-fallow-argument-mismatch" to the compilation flags (as mentioned in the link above) seems to fix the issue. I thought I'd share this here, though, in case others run into the same issue and get stuck.

### Code versions
- gfortran: 11.1
- Operating System: Mac OS
- Python: 3.9
- OpenMPI: 4.0
- CGNS: 4.2.0
- PETSc: 3.15.5

**Comment by nwu63** [comment]
Thanks for opening this issue Chris. We're aware of this but we do not add that compiler flag to the config files because we do not officially support GCC 10+, where this flag was introduced (and the behaviour changed). I'm going to close this issue since we're not going to address it in the immediate future, but others who have the same issue will hopefully see this by searching.
