### ISSUE TITLE
Update default options

### ISSUE THREAD

**Issue by nwu63** [mdolab/adflow#191]
# Description of feature
I would like to propose some changes to default ADflow options, and start some discussions.
- `MGCycle` -> `sg`
- `printTiming` -> `False`
- `writeVolumeSolution` -> `False`
- `useNKSolver` -> `True`

**Comment by sseraj** [comment]
> `MGCycle` -> `sg`

I would support this change. We have already made ANK the default solver, so skipping the multigrid startup by default makes sense to me.

> `printTiming` -> `False`

I don't have a strong opinion on this one. I don't really look at the timings, but they also don't take up too much space in the output.

> `writeVolumeSolution` -> `False`

I think this is better kept as True. I would find it pretty strange if a CFD solver did not produce volume output by default.

> `useNKSolver` -> `True`

I suggested this change back in #41. The conclusion then was that the NK solver is not robust, so the user needs to tune `NKSwitchTol` to get it to work. If we do end up turning it on by default, we should also tighten the default `NKSwitchTol` (maybe to 1e-8 so it is effectively turned off unless the user tightens the default `L2Convergence`.

**Comment by yqliaohk** [comment]
> * `writeVolumeSolution` -> `False`

I think it would be better to write out the volume solutions only to avoid too many output files. To accommodate that, I am thinking maybe we should separate evaluating and outputting the surface, lift, and slice files as a post process step by using the volume solutions rather than as part of the solving process.

**Comment by nwu63** [comment]
I generally don't write out volume files since they are quite big, especially for optimizations. But I'm okay with keeping this option if people find it useful. As for postprocessing, I don't personally mind having many output files, and the current setup saves an additional step. I think it might be more worthwhile to fix issues such as #69 regarding the lift/span files.

**Comment by anilyil** [comment]
I agree with the `MGCycle`, but disagree with the others: 
- `printTiming`: I think it's still good to have because it will force people to look at how long the solution took. For a beginner that can be a good red flag to see if stuff is taking too long or not. Plus its only cosmetic so I say we keep it enabled.
- `writeVolumeSolution`: I agree with Sabet. 
- `useNKSolver`: For optimizations I am rarely using the NK solver for even moderately challenging cases. It has a few failure modes that it cannot recover from, so I just default to ANK. For some cases, even a 1e-8 switch might not be tight enough so its difficult. I am mixed on this one but would rather keep the default to preserve the default behavior.

**Comment by marcomangano** [comment]
Just chiming in to say that I agree with Anil and Sabet. I barely use NK in my runs, and I think it's fine to have the timing printed by default. I would be in favor of finding a way to print "selected" volume solution files (e.g. major optimization iterations, or just initial and final solutions) but this goes beyond the scope of this issue and standalone ADflow

**Comment by joanibal** [comment]
I don't have much else to add. We probably should not change options without an overwhelming consensus. It sounds like changing `MGCycle` is the only thing we agree on.
