### ISSUE TITLE
Migration to Testflo for regression testing

### ISSUE THREAD

**Issue by anilyil** [mdolab/adflow#28]
## Type of issue

- Other: Code modifications required to change the underlying testing suite to testflo.

## Description

This issue will contain the discussions regarding the migration of adflow testing to testflo. The modifications in PR #26 to migrate the testing suite to testflo is missing a number of important features. The development related to this will be pulled into the testflo branch of adflow, and the changes will be merged to the master branch once all expected functionality is provided.

### Current behavior

Here is a list of issues (in no particular order) that I think should be addressed. This is not an exhaustive list and we will have the discussions related to these items in this issue page.

1. Individual tests do not provide feedback as they finish, which makes it difficult to determine the current progress.
2. Tests don't run in order, e.g. test 18 runs before test 1, etc.
3. No complex tests.
4. No output from tests. The output from the test runs should go into a file for each test for easier debugging.
5. No documentation on obtaining the input files required for tests. Existing documentation for input files is in a readme file in a directory that is a few levels down the main directory. There are no external links (that I could see) to this readme. The directory name is changed from inputFiles to input_files
6. It's not clear how many processors is used for each test. This may be related to testflo, but either way, this should be clearly documented.
7. If multiple tests run at the same time, it should be guaranteed that tests do not try to over-write to same output files.
8. The tests generate a lot of intermediate files that are not cleaned up and appear in the git status.
9. No documentation in general for simple testflo options.
10. If a value does not match in the reg tests, the output should also state what the value means (dot product test of this routine etc.).
11. Old test file and folder structure are still there.

### Expected behavior

Here is a list of expected behavior for all the issues I raised above (with the same numbering):

1. Individual tests should provide feedback as they finish, regardless of them failing or succeeding. 
2. Tests should run in order, e.g. test 1, then 2, then 3, up to 18. Although this is not strictly required, it will become tricky to figure out when a particular test ran if this order is not followed. If tests run in order, I know that test 3 did not run yet since test 2 is still running. If this order is not preserved, I would need to go through the full output to see if that particular test ran already. This will become a larger issue as we add more tests.
3. The suite should also contain complex tests. 
4. Each test should write its output to an output file for easier debugging. These files can be put in a folder, which should be included in the gitignore list.
5. Documentation needs to be greatly improved. The readme file in the root adflow directory should point to the testing documentation directly. This documentation should include directions on how to obtain the input files. The documentation should also include various testflo options that can be used to run the tests, and possibly contain a link to the testflo documentation itself.
6. It should be very clear how the tests are run, with how many processors. "each test runs on 4 processors" is not enough information. Do they run in serial or parallel? How does testflo determine how many tests to run in parallel. The documentation should include the options to specify the exact numbers of how many processor per test, and how many tests at a given instance. 
7. The tests should not include any i/o race, and use different output files. Same input files are ok.
8. The intermediate files created as the tests run should be deleted by default. There should be an option to prevent this cleanup to keep the files in place. If this is not possible, the files should be moved to a folder (by changing the output directory in tests). In both of these scenarios, any intermediate file that gets created should be included in the gitignore list.
9. The documentation should include a few useful testflo options.
10. When a value does not meet the tolerance, the description of the value should be printed for easier debugging.
11. All of the old test files and any references to them should be removed.

**Comment by joanibal** [comment]
Hey Anil, thanks for creating a place for this discussion.

I think a big issue here is that the README.md included in the PR was not the most up to date version. The [README.md on my fork](https://github.com/joanibal/adflow/blob/master/tests/README.md) includes additional work done by folks. 

1) To enable screen output use the -s argument. This will print data to the screen like a normal adflow run script. 
2) I don't agree that the test should be in run "in order". Ideally we would transition away from non-descriptive test names like "1", "2", and "3" to "tutorial_wing_analysis" and "crm_adjoint". Furthermore, to change the order the test are run when calling `testflo reg_tests` would require a change to testflo since it runs tests concurrently by default. 
3) Agreed, we are working toward that
4)  I don't agree that this should be done by default. Since tests are run concurrently if you were to just redirect the stdout into a file it would mostly look like a garbled mess. You could run the test non concurrently and save the output, but then you are loosing some of the benefits of testflo. If you want to understand why a test may be failing in greater detail than is provided in the error message you can just rerun that test and examine the output. I don't see a great need to save the outputs automatically, especially considering the tests should be quick to run.  
5) Agreed. Some improvements have been made in the more up to date README.md, but more improvements can be made.
6) You can chose the total number of processors to use using the `-n` argument. Each test file includes the number of processors to use in the N_PROCS attribute of the testing class, so it is stated explicitly for each test. 
 7) Is there a case where this is happening? If so, it sounds like an easy fix to set unique output names for each test.
8) Don't think clean up should be done by default. I see that leading to some confusion for someone unfamiliar with the tests. Would could make a script to do the clean up that users could run if they wanted and also add the files to .gitignore .
9) Agreed, see 5)
10) Agreed, this is already being worked on 
11) Agreed, but probably should be the last thing we do

**Comment by anilyil** [comment]
4. if you can easily get the output with -s, then we probably dont need the output going to a file. Users can do it themselves
7. I did not check, possibly not an issue now but just a heads up. I saw this happen for another code in the past.
8. No cleanup is fine. Adding the auxiliary output to gitignore is enough

Finally, I took a look at the README.md file on your fork. It has more detail but I have other problem with it. The first bullet point should be the default command to run the tests, and people should not need to read and try to understand what each case means. An incoming student might not understand what "training" a test would do. We can say use this command to run the tests and the expected output.

**Comment by joanibal** [comment]
@anilyil  How do you feel about point 2? Not running the test in any particular order?

**Comment by anilyil** [comment]
I agree with your previous comments regarding that. What you said makes sense

**Comment by nwu63** [comment]
Have these concerns been addressed with the recent adoption of testflo?

**Comment by joanibal** [comment]
@anilyil Can this issue be closed or does it need more work?

**Comment by eirikurj** [comment]
As discussed its seems that the tests are using a non-existent function `setRef` from `BaseRegTest`. Before closing this one we should settle on an API for `BaseRegTest` and then adjust the tests here.
This issue also brings up the need for "testing" the training process, i.e., make sure we can actually run the training regularly.

**Comment by anilyil** [comment]
Seems like the PRs addressed all of the points I made earlier in this issue, so this issue can be closed if there is no new items. @eirikurj I am not up to date on what you are referring to, so if you can open that issue, we can close this one.

**Comment by nwu63** [comment]
He's talking about how ADflow training routines `testflo -m "train*" .` are broken. I am aware of the issue and am working with @joanibal to fix it. Closing now.
