### ISSUE TITLE
Spectral Radii zeroed after getResiduals() with blockettes

### ISSUE THREAD

**Issue by joanibal** [mdolab/adflow#32]
## Type of issue
Bug 

## Description
After you instantiate an ADflow instance with a restart file.
If you call

CFDSolver.getResiduals(ap)
CFDSolver.computeJacobianVectorProductBwd(....)

you get the wrong answer

But if you call

CFDSolver.getResiduals(ap)
CFDSolver.computeJacobianVectorProductFwd(....)
CFDSolver.computeJacobianVectorProductBwd(....)

you get the right answer

If you trace the error back you see that this is because the spectral radii (radI, radJ, radK) aren't set by getResiduals() with the default options

If you set the option `useblockettes' to False there is no issue. So it seems like the spectral radii are being zeroed before use in master_b when using blockettes.

if you add an extra call to timeStep_block at the beginning of master_b()
it fixes the issue. So i'm very certain it is because of the radii

### Expected behavior
Both should give the same answer

### Code version (if relevant)
**Python version:** 2.7
**External dependencies:** 
Petsc 3.11
OpenMPI 3.1.4

**Internal packages:** …
latest of everything

**Comment by joanibal** [comment]
@anilyil

**Comment by anilyil** [comment]
The ambiguity is caused by the "getResiduals" call returning only the residuals, and not guaranteeing any intermediate variable being up to date. getResiduals does work correctly, it should return the correct residuals. However, if you run it with the blockette version of the residuals, as you saw, it will not update some of the intermediate variables. 

This issue does not come up if you actually call the CFD solver. We did run into this while coding the blockette stuff, and we fixed this particular problem by adding an extra call to the timestep computation in the solvestate subroutine: https://github.com/mdolab/adflow/blob/master/src/solver/solvers.F90#L1025 Having this extra call makes sure that spectral radii are explicitly computed and saved, regardless of the blockette flag.

My proposed solution: Seems like the getRes subroutine in NKSolvers (https://github.com/mdolab/adflow/blob/master/src/NKSolver/NKSolvers.F90#L1374) is only called by the getResiduals method on the python level. We can modify this subroutine to perform an extra call to timestep if blockette flag is enabled. This way, spectral radii will be up to date. Another option is to only call the non-blockette residual in this getRes subroutine.

There are multiple ways to fix this issue. I can make this modification, but first, let me know what you think about this.

**Comment by joanibal** [comment]
Why are the spectral radii not saved during getRes when using blockettes? 
Is there a reason why it should/must be done this way?

**Comment by anilyil** [comment]
With blockettes, we want to have as minimal data copying between the cached memory and actual memory as possible. Therefore, almost all intermediate variables that are computed during the blockette residual call stays in the cached arrays and gets overwritten at the next blockette. We only copy out two variables: residuals (dw) and time step (dtl) from the cached memory back to the main memory.

We can also include a flag to copy out the spectral radii from cached memory after we compute it; however, we do not want to do this for every residual evaluation since it will just slow things down. 

I am currently trying to figure out where the spectral radii stuff is put into the main memory, after the solution converges. This is not exactly the issue you ran into but there is a chance that the arrays in the main memory not being up to date after flow convergence.

**Comment by joanibal** [comment]
Ok, I'm starting to think that instead of modifying getResiduals. We need another routine to to call to propagate the value of the states through the code and set intermediate variables. Perhaps the best thing to do is to make the master routine callable from python 

Do you agree?

**Comment by anilyil** [comment]
To test, I modified the blockette code to copy the radi radj and radk variables from the blockette memory to main memory. As expected, this fixes this issue (and any similar issues due to these variables being out of date). This way, the case mentioned here works regardless of the useblockettes flag. Also, this shows that radi radj and radk are the only intermediate variables that we missed and I dont think there are other intermediate variables we forgot to copy out from the blockette memory.
