### ISSUE TITLE
Request for WIndows Binary 

### ISSUE THREAD

**Issue by hknarahari** [mdolab/adflow#74]
It is not an issue but a humble request from a CFD teacher. Most of my students use laptops and Windows 10 environment. It would be a great help if a vanila version of the .exe for windows 10 code is included . Hence this request which can help the students explore MDO option along with CFD first and explore the code eventually.  Apologies for such a dumb request ..
Thanks in advance
Narahari
_

**Comment by nwu63** [comment]
Hi,

Unfortunately supporting Windows and providing pre-compiled binaries is a rather complex task, particularly for CFD software since there tend to be complex dependencies. As a research lab we do not have the resources to support that use case. However, there are two possibilities to running ADflow on Windows:
- Use WSL to directly compile ADflow within the Linux subsystem under Windows. This is possible and has been done before successfully
- Use the docker containers we provide, which contains a bare Ubuntu OS with ADflow pre-compiled including all its dependencies, so you can run basic aerodynamic shape optimization out of the box. Note that this is an experimental feature since we use it purely to test our codes, so the exact workflow when using it to run optimizations has to be figured out.

For CFD education, I think if the goal is to learn how to run CFD programs, then perhaps a commercial software with dedicated Windows support is the best approach. But for learning how to write CFD code, then I'm afraid the vast majority of us will use Linux for very obvious reasons.

**Comment by hknarahari** [comment]
Thank you for the quick response. I will try both options and update on the results.
Narahari
